export const GET_COURSES = 'COURSES/GET_COURSES';
export const ADD_COURSE = 'COURSES/ADD_COURSE';
export const REMOVE_COURSE = 'COURSES/REMOVE_COURSE';
export const UPDATE_COURSE = 'COURSES/UPDATE_COURSE';
